# Generated by Django 3.2.2 on 2021-05-08 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Habit', '0001_initial'),
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(default=1, editable=False)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='Category.category')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='Habit.habit')),
            ],
        ),
    ]
