# Generated by Django 3.2.2 on 2021-05-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Day', '0002_remove_day_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
