# Generated by Django 3.2.2 on 2021-05-08 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Habit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='finish_date',
            new_name='end_date',
        ),
    ]
